### ISSUE TITLE
Not a bug, just a question

### ISSUE THREAD

**Issue by chmonyasik** [TelepathicGrunt/StructureLayoutOptimizer#2]
Hello! Wanted to ask if it’s possible and beneficial to use your mod (Structure Layout Optimizer) together with Structure Essentials by someaddon? It’s a bit of a tricky question since Structure Essentials is closed source, but perhaps you have some opinion or thoughts on this. Thank you so much in advance!

**Comment by TelepathicGrunt** [comment]
They will not interfere as far as I know. My mod aims to do optimizations lower down. Their mod does not seem to optimize structure generation. But best way to know is to just try the two mods together
