### ISSUE TITLE
[1.20.1-Forge]Crash on launch

### ISSUE THREAD

**Issue by Git-Reternos** [TelepathicGrunt/StructureLayoutOptimizer#7]
[latest.log](https://github.com/user-attachments/files/18272580/latest.log)

**Comment by TelepathicGrunt** [comment]
Fricken forge 1.20.1 builds have been giving me nothing but issues.

**Comment by TelepathicGrunt** [comment]
Fixed now in 1.0.7 by switching off of garbage ForgeGradle to Legacy ModDevGradle so it can actually build the jar correctly. ForgeGradle is just broken so I will place all the blame on that.

eed367e5f5ecf0158ddf6092475fdee8f899f22e
8348bf8f31465e261d0ae3296fb50c06a9f5e2da
ec69ed05b1ff9cfd6eb779a00ee9b9ea7025ebde
2daabf4f9a1349346e377311dee099de27f83771

**Comment by Git-Reternos** [comment]
It got fixed. Thanks for your effort
