### ISSUE TITLE
Wrong non-obsfucated jar is uploaded for Forge 1.20.1 and will not work in prod

### ISSUE THREAD

**Issue by Kingdemonic666** [TelepathicGrunt/StructureLayoutOptimizer#8]
When generating new chunks in one of the Blue Skies dimensions (only tried Everdawn so far) the game will crash when it tries to generate a certain structure from the mod.
The issue could be related to the library mod Structure Gel API, but I'm not sure.
Crash Log: [crash-2024-12-30_15.01.53-server.txt](https://github.com/user-attachments/files/18276893/crash-2024-12-30_15.01.53-server.txt)

**Comment by brisingraerowing** [comment]
I also get this crash, but without Blue Skies.

[Crash Log](https://mclo.gs/6LnDisc)

**Comment by TelepathicGrunt** [comment]
Apologies, the issue is in the switch to Legacy ModDevGradle, the jar I uploaded is not the reobfs jar needed to run in prod. I hate working on 1.20.1 Forge. v1.0.8 fixes this

fa8da29363eca6d6e928eebf4518c4c3b06b3d78
