### ISSUE TITLE
Mod failed to load correctly

### ISSUE THREAD

**Issue by ecstatic-star** [TelepathicGrunt/StructureLayoutOptimizer#9]
Here's the log file you asked for
[Latest log.txt](https://github.com/user-attachments/files/18282434/Latest.log.txt)

**Comment by TelepathicGrunt** [comment]
Update to v1.0.8 Structure Layout Optimizer. This crash should be fixed in that version. I tested it myself

**Comment by ecstatic-star** [comment]
it didint work here's an Screenshot

![Zrzut ekranu 2024-12-31 164250](https://github.com/user-attachments/assets/a4879e49-a90a-4484-8966-107fd83dae8f)

**Comment by TelepathicGrunt** [comment]
Open up your mods folder and make sure there is only one jar for my mod. `structure_layout_optimizer-forge-1.0.8.jar` is what should be in the mods folder and not 1.0.7 or 1.0.6.

Here's a picture of the mod working for me
![image](https://github.com/user-attachments/assets/89674086-1ece-40bf-85fb-1df96a561c7e)

The error you showed from the logs is what 1.0.7 was causing

**Comment by TelepathicGrunt** [comment]
actually, try updating forge to latest forge like 47.3.22

**Comment by TelepathicGrunt** [comment]
I just remember I lowed the required for from 47.3.12 to 47.3.0 but forgot I was using a feature that was introduced in 47.3.12 Forge. So you must use forge 47.3.12 or newer for the mod to work. I'll put back the restriction so it gives a better error message

**Comment by ecstatic-star** [comment]
oh. okey I willt try and tell you the results in some minutes

**Comment by ecstatic-star** [comment]
about it, I tried puting only that mod into an clean modpack and it worked. but when i put this mod into my it stoped working, for some reason instead of saying its incompatible with my mods it just said "failed to load correctly" , soory for wasting your time as I didin't know that this mod was incompatible with others from my modpack

**Comment by TelepathicGrunt** [comment]
it shouldn't be incompatible. Can you send me your modpack please? Whether that be an export to google drive or dropbox or a modlist if it isn't many mods

**Comment by ecstatic-star** [comment]
oh my god....i forgot to change the forge version on MY modpack thats why it didint work. im really soory for the confusion i have made. It works fine now, im thankful for your time and you're help

**Comment by TelepathicGrunt** [comment]
Ah that explains it lol. I'll close this now. Enjoy!

**Comment by ecstatic-star** [comment]
Thanks a lot
